services:
  database:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: .
    container_name: java_backend
    restart: always
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/biblioteca
      - SPRING_DATASOURCE_USERNAME="${USER}"
      - SPRING_DATASOURCE_PASSWORD="${PASSWORD}"
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - database

volumes:
  pgdata:
  
